uploads = []
generated = []

[[outputs]]
id = "U4DOGsdvvqvf_gvvRjPN8"
uri = "file://love-site-netlify.tar.gz"
type = "unspecified"
title = "Love Site — Netlify Build"

[[outputs]]
id = "_giadTmqNDUhw83LXajjE"
uri = "file://artifacts/love-site/love-site-netlify.zip"
type = "unspecified"
title = "love-site-netlify.zip — drag & drop to Netlify"

[[outputs]]
id = "RRFzBczIB3ozT_rJMWw3U"
uri = "file://artifacts/love-site/love-site.tar.gz"
type = "unspecified"
title = "Love Site — Production Build"
